export enum TokenType {
    VOID = "void", // nothing to tokenize

    UNKNOWN = "unknown",

    IDENTIFIER = "identifier",
    INTEGER = "integer",
    SPACE = "space",
    TABULATION = "tabulation",
    VERTICAL_TABULATION = "vertical tabulation",
    CARRIAGE_RETURN = "carriage return",
    LINE_FEED = "line feed",
    CRLF = "carriage return + line feed",
    FORM_FEED = "form feed",
    DOT = "dot",
    COMMA = "comma",
    COLON = "colon",
    SEMICOLON = "semicolon",
    DOUBLE_QUOTATION_MARK = "double quotation mark",
    EQUAL_SIGN = "equal sign",
    QUESTION_MARK = "question mark",
    EXCLAMATION_MARK = "exclamation mark",
    ASTERISK = "asterisk",
    PLUS_SIGN = "plus sign",
    HYPHEN = "hyphen",
    UNDERSCORE = "underscore",
    SLASH = "slash",
    BACKSLASH = "backslash",
    OPEN_PARENTHESIS = "open parenthesis",
    CLOSE_PARENTHESIS = "close parenthesis",
    OPEN_SQUARE_BRACKET = "open square bracket",
    CLOSE_SQUARE_BRACKET = "close square bracket",
    OPEN_CURLY_BRACKET = "open curly bracket",
    CLOSE_CURLY_BRACKET = "close curly bracket",
    OPEN_ANGLE_BRACKET = "open angle bracket",
    CLOSE_ANGLE_BRACKET = "close angle bracket",
    AMPERSAND = "ampersand",
    TILDE = "tilde",
    HASH_SIGN = "hash sign",
    CARET_SIGN = "caret sign",
    PERCENT_SIGN = "percent sign",
    AROBASE = "arobase",
    DOLLAR = "dollar",

    // never (or rarily?) used in HTTP
    SINGLE_QUOTATION_MARK = "single quotation mark",
    BACK_QUOTATION_MARK = "back quotation mark",
    PIPE = "pipe",
    BACKSPACE = "backspace",
    NULL = "null",
};
