import {
    HTTPHeaderValueAccept,
    HTTPHeaderValueAcceptCH,
    HTTPHeaderValueAcceptCharset,
    HTTPHeaderValueAcceptEncoding,
    HTTPHeaderValueAcceptLanguage,
    HTTPHeaderValueAcceptRanges,
    HTTPHeaderValueAccessControlAllowCredentials,
    HTTPHeaderValueAccessControlAllowHeaders,
    HTTPHeaderValueAccessControlAllowMethods,
    HTTPHeaderValueAccessControlAllowOrigin,
    HTTPHeaderValueAccessControlExposeHeaders,
    HTTPHeaderValueAccessControlMaxAge,
    HTTPHeaderValueAccessControlRequestHeaders,
    HTTPHeaderValueAccessControlRequestMethod,
    HTTPHeaderValueAge,
    HTTPHeaderValueAllow,
    HTTPHeaderValueAltSvc,
    HTTPHeaderValueAuthorization,
    HTTPHeaderValueCacheControl,
    HTTPHeaderValueClearSiteData,
    HTTPHeaderValueConnection,
    HTTPHeaderValueContentDisposition,
    HTTPHeaderValueContentEncoding,
    HTTPHeaderValueContentLanguage,
    HTTPHeaderValueContentLength,
    HTTPHeaderValueContentLocation,
    HTTPHeaderValueContentRange,
    HTTPHeaderValueContentSecurityPolicy,
    HTTPHeaderValueContentSecurityPolicyReportOnly,
    HTTPHeaderValueContentType,
    HTTPHeaderValueCookie,
    HTTPHeaderValueCrossOriginEmbedderPolicy,
    HTTPHeaderValueCrossOriginOpenerPolicy,
    HTTPHeaderValueCrossOriginResourcePolicy,
    HTTPHeaderValueDate,
    HTTPHeaderValueDownlink,
    HTTPHeaderValueEarlyData,
    HTTPHeaderValueECT,
    HTTPHeaderValueETag,
    HTTPHeaderValueExpect,
    HTTPHeaderValueExpectCT,
    HTTPHeaderValueExpires,
    HTTPHeaderValueForwarded,
    HTTPHeaderValueFrom,
    HTTPHeaderValueHost,
    HTTPHeaderValueIfMatch,
    HTTPHeaderValueIfModifiedSince,
    HTTPHeaderValueIfNoneMatch,
    HTTPHeaderValueIfRange,
    HTTPHeaderValueIfUnmodifiedSince,
    HTTPHeaderValueKeepAlive,
    HTTPHeaderValueLastEventID,
    HTTPHeaderValueLastModified,
    HTTPHeaderValueLink,
    HTTPHeaderValueLocation,
    HTTPHeaderValueMaxForwards,
    HTTPHeaderValueNEL,
    HTTPHeaderValueOrigin,
    HTTPHeaderValuePermissionsPolicy,
    HTTPHeaderValuePragma,
    HTTPHeaderValueProxyAuthenticate,
    HTTPHeaderValueProxyAuthorization,
    HTTPHeaderValueRange,
    HTTPHeaderValueReferer,
    HTTPHeaderValueReferrerPolicy,
    HTTPHeaderValueReportTo,
    HTTPHeaderValueRetryAfter,
    HTTPHeaderValueRTT,
    HTTPHeaderValueSaveData,
    HTTPHeaderValueSecCHUA,
    HTTPHeaderValueSecCHUAArch,
    HTTPHeaderValueSecCHUABitness,
    HTTPHeaderValueSecCHUAMobile,
    HTTPHeaderValueSecCHUAModel,
    HTTPHeaderValueSecCHUAPlatform,
    HTTPHeaderValueSecCHUAPlatformVersion,
    HTTPHeaderValueSecFetchDest,
    HTTPHeaderValueSecFetchMode,
    HTTPHeaderValueSecFetchSite,
    HTTPHeaderValueSecFetchUser,
    HTTPHeaderValueSecWebSocketAccept,
    HTTPHeaderValueSecWebSocketKey,
    HTTPHeaderValueSecWebSocketVersion,
    HTTPHeaderValueServer,
    HTTPHeaderValueServerTiming,
    HTTPHeaderValueServiceWorkerNavigationPreload,
    HTTPHeaderValueSetCookie,
    HTTPHeaderValueSourceMap,
    HTTPHeaderValueStrictTransportSecurity,
    HTTPHeaderValueTE,
    HTTPHeaderValueTimingAllowOrigin,
    HTTPHeaderValueTrailer,
    HTTPHeaderValueTransferEncoding,
    HTTPHeaderValueUpgrade,
    HTTPHeaderValueUpgradeInsecureRequests,
    HTTPHeaderValueUserAgent,
    HTTPHeaderValueVary,
    HTTPHeaderValueVia,
    HTTPHeaderValueWWWAuthenticate,
    HTTPHeaderValueXContentTypeOptions,
    HTTPHeaderValueXDNSPrefetchControl
} from './header-values.types';

export type HTTPHeaderMap = {
    "WWW-Authenticate"?: HTTPHeaderValueWWWAuthenticate,
    "Authorization"?: HTTPHeaderValueAuthorization,
    "Proxy-Authenticate"?: HTTPHeaderValueProxyAuthenticate,
    "Proxy-Authorization"?: HTTPHeaderValueProxyAuthorization,
    "Age"?: HTTPHeaderValueAge,
    "Cache-Control"?: HTTPHeaderValueCacheControl,
    "Clear-Site-Data"?: HTTPHeaderValueClearSiteData,
    "Expires"?: HTTPHeaderValueExpires,
    "Pragma"?: HTTPHeaderValuePragma,
    "Accept-CH"?: HTTPHeaderValueAcceptCH,
    "Sec-CH-UA"?: HTTPHeaderValueSecCHUA,
    "Sec-CH-UA-Arch"?: HTTPHeaderValueSecCHUAArch,
    "Sec-CH-UA-Bitness"?: HTTPHeaderValueSecCHUABitness,
    "Sec-CH-UA-Mobile"?: HTTPHeaderValueSecCHUAMobile,
    "Sec-CH-UA-Model"?: HTTPHeaderValueSecCHUAModel,
    "Sec-CH-UA-Platform"?: HTTPHeaderValueSecCHUAPlatform,
    "Sec-CH-UA-Platform-Version"?: HTTPHeaderValueSecCHUAPlatformVersion,
    "Downlink"?: HTTPHeaderValueDownlink,
    "ECT"?: HTTPHeaderValueECT,
    "RTT"?: HTTPHeaderValueRTT,
    "Early-Data"?: HTTPHeaderValueEarlyData,
    "Save-Data"?: HTTPHeaderValueSaveData,
    "Last-Modified"?: HTTPHeaderValueLastModified,
    "ETag"?: HTTPHeaderValueETag,
    "If-Match"?: HTTPHeaderValueIfMatch,
    "If-None-Match"?: HTTPHeaderValueIfNoneMatch,
    "If-Modified-Since"?: HTTPHeaderValueIfModifiedSince,
    "If-Unmodified-Since"?: HTTPHeaderValueIfUnmodifiedSince,
    "Vary"?: HTTPHeaderValueVary,
    "Connection"?: HTTPHeaderValueConnection,
    "Keep-Alive"?: HTTPHeaderValueKeepAlive,
    "Accept"?: HTTPHeaderValueAccept,
    "Accept-Charset"?: HTTPHeaderValueAcceptCharset,
    "Accept-Encoding"?: HTTPHeaderValueAcceptEncoding,
    "Accept-Language"?: HTTPHeaderValueAcceptLanguage,
    "Expect"?: HTTPHeaderValueExpect,
    "Max-Forwards"?: HTTPHeaderValueMaxForwards,
    "Cookie"?: HTTPHeaderValueCookie,
    "Set-Cookie"?: HTTPHeaderValueSetCookie,
    "Access-Control-Allow-Origin"?: HTTPHeaderValueAccessControlAllowOrigin,
    "Access-Control-Allow-Credentials"?: HTTPHeaderValueAccessControlAllowCredentials,
    "Access-Control-Allow-Headers"?: HTTPHeaderValueAccessControlAllowHeaders,
    "Access-Control-Allow-Methods"?: HTTPHeaderValueAccessControlAllowMethods,
    "Access-Control-Expose-Headers"?: HTTPHeaderValueAccessControlExposeHeaders,
    "Access-Control-Max-Age"?: HTTPHeaderValueAccessControlMaxAge,
    "Access-Control-Request-Headers"?: HTTPHeaderValueAccessControlRequestHeaders,
    "Access-Control-Request-Method"?: HTTPHeaderValueAccessControlRequestMethod,
    "Origin"?: HTTPHeaderValueOrigin,
    "Timing-Allow-Origin"?: HTTPHeaderValueTimingAllowOrigin,
    "Content-Disposition"?: HTTPHeaderValueContentDisposition,
    "Content-Length"?: HTTPHeaderValueContentLength,
    "Content-Type"?: HTTPHeaderValueContentType,
    "Content-Encoding"?: HTTPHeaderValueContentEncoding,
    "Content-Language"?: HTTPHeaderValueContentLanguage,
    "Content-Location"?: HTTPHeaderValueContentLocation,
    "Forwarded"?: HTTPHeaderValueForwarded,
    "Via"?: HTTPHeaderValueVia,
    "Location"?: HTTPHeaderValueLocation,
    "From"?: HTTPHeaderValueFrom,
    "Host"?: HTTPHeaderValueHost,
    "Referer"?: HTTPHeaderValueReferer,
    "Referrer-Policy"?: HTTPHeaderValueReferrerPolicy,
    "User-Agent"?: HTTPHeaderValueUserAgent,
    "Allow"?: HTTPHeaderValueAllow,
    "Server"?: HTTPHeaderValueServer,
    "Accept-Ranges"?: HTTPHeaderValueAcceptRanges,
    "Range"?: HTTPHeaderValueRange,
    "If-Range"?: HTTPHeaderValueIfRange,
    "Content-Range"?: HTTPHeaderValueContentRange,
    "Cross-Origin-Embedder-Policy"?: HTTPHeaderValueCrossOriginEmbedderPolicy,
    "Cross-Origin-Opener-Policy"?: HTTPHeaderValueCrossOriginOpenerPolicy,
    "Cross-Origin-Resource-Policy"?: HTTPHeaderValueCrossOriginResourcePolicy,
    "Content-Security-Policy"?: HTTPHeaderValueContentSecurityPolicy,
    "Content-Security-Policy-Report-Only"?: HTTPHeaderValueContentSecurityPolicyReportOnly,
    "Expect-CT"?: HTTPHeaderValueExpectCT,
    "Permissions-Policy"?: HTTPHeaderValuePermissionsPolicy,
    "Strict-Transport-Security"?: HTTPHeaderValueStrictTransportSecurity,
    "Upgrade-Insecure-Requests"?: HTTPHeaderValueUpgradeInsecureRequests,
    "X-Content-Type-Options"?: HTTPHeaderValueXContentTypeOptions,
    "Sec-Fetch-Site"?: HTTPHeaderValueSecFetchSite,
    "Sec-Fetch-Mode"?: HTTPHeaderValueSecFetchMode,
    "Sec-Fetch-User"?: HTTPHeaderValueSecFetchUser,
    "Sec-Fetch-Dest"?: HTTPHeaderValueSecFetchDest,
    "Service-Worker-Navigation-Preload"?: HTTPHeaderValueServiceWorkerNavigationPreload,
    "Last-EventID"?: HTTPHeaderValueLastEventID,
    "NEL"?: HTTPHeaderValueNEL,
    "Report-To"?: HTTPHeaderValueReportTo,
    "Transfer-Encoding"?: HTTPHeaderValueTransferEncoding,
    "TE"?: HTTPHeaderValueTE,
    "Trailer"?: HTTPHeaderValueTrailer,
    "Alt-Svc"?: HTTPHeaderValueAltSvc,
    "Date"?: HTTPHeaderValueDate,
    "Link"?: HTTPHeaderValueLink,
    "Retry-After"?: HTTPHeaderValueRetryAfter,
    "Server-Timing"?: HTTPHeaderValueServerTiming,
    "SourceMap"?: HTTPHeaderValueSourceMap,
    "Upgrade"?: HTTPHeaderValueUpgrade,
    "X-DNS-Prefetch-Control"?: HTTPHeaderValueXDNSPrefetchControl,
    "Sec-WebSocket-Accept"?: HTTPHeaderValueSecWebSocketAccept,
    "Sec-WebSocket-Key"?: HTTPHeaderValueSecWebSocketKey,
    "Sec-WebSocket-Version"?: HTTPHeaderValueSecWebSocketVersion,
    [key: string]: any,
};
